### ISSUE TITLE
Resume docking

### ISSUE THREAD

**Issue by rafaeltiveron** [lightdock/lightdock-python2.7#27]
Hi

Is there a way to resume docking process? Any command?

Thank you

**Comment by brianjimenez** [comment]
Hi @rafaeltiveron 

Sorry, but at this moment there is not. There was an old script called `relightdock.py` in the past, but it was very experimental and we decided to remove it to avoid confusion.

This is an important enhancement, but not trivial to code. We will develop this in a future release.

**Comment by brianjimenez** [comment]
This won't be implemented in the Python 2.7 version as it has been deprecated.
